kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: system
data:
  config: |
    job:
      autoDelTime: 30
      backLimit: 5
      image: kubespheredev/kubeeye-job:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
      multiCluster:
        member1: 
          image: kubespheredev/kubeeye-job:latest
          imagePullPolicy: IfNotPresent