apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kubeeye-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: kubeeye-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: kubeeye-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: kubeeye-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - args:
        - --leader-elect
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1500m
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
          - mountPath: /kubeeye/data
            name: inspect-result
          - mountPath: /etc/localtime
            name: localtime
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: inspect-result
          persistentVolumeClaim:
            claimName: inspect-result
        - name: localtime
          hostPath:
            path: /etc/localtime