apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inspect-result
  namespace: system
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
          storage: 10Gi

