# permissions for end users to edit auditplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspectplan-editor-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspectplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspectplans/status
  verbs:
  - get
