# permissions for end users to edit audittasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspecttask-editor-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspecttasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspecttasks/status
  verbs:
  - get
