# permissions for end users to view auditplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspectplan-viewer-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspectplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - inspectplans/status
  verbs:
  - get
